[platformio]
default_envs = dino_lampe

[env:dino_lampe]
board = d1_mini_pro
platform = ${common.platform_wled_default}
platform_packages = ${common.platform_packages}
board_build.ldscript = ${common.ldscript_4m1m}
build_unflags = ${common.build_unflags}
build_flags = ${common.build_flags} ${esp8266.build_flags}
  -D WLED_RELEASE_NAME=\"DinoLampe\"
  
  ; === NETWORK & SMART HOME DEAKTIVIEREN ===
  -D WLED_DISABLE_ALEXA          ; Alexa Sprachsteuerung aus
  -D WLED_DISABLE_HUESYNC        ; Philips Hue Sync aus
  -D WLED_DISABLE_INFRARED       ; Infrarot-Empfaenger aus
  -D WLED_DISABLE_LOXONE         ; Loxone Smart Home aus
  -D WLED_DISABLE_MQTT           ; MQTT aus
  -D WLED_DISABLE_BYNIGHT        ; Nightlight-Modus aus
  -D WLED_DISABLE_ESPNOW         ; ESP-NOW Sync aus

  ; === PROTOKOLLE & SCHNITTSTELLEN DEAKTIVIEREN ===
  -D WLED_DISABLE_HYPERION       ; Hyperion Ambilight aus
  -D WLED_DISABLE_UDP            ; WLED-zu-WLED Sync aus
  -D WLED_DISABLE_E131           ; DMX / E1.31 Streaming aus
  -D WLED_DISABLE_ARTNET         ; Art-Net Protokoll aus
  -D WLED_DISABLE_IMPROV         ; Bluetooth/Serial Wifi Improv setup aus

  ; === EFFEKTE & MATRIX (2D) DEAKTIVIEREN ===
  -D WLED_DISABLE_2D             ; 2D Matrix-Verarbeitung komplett aus
  -D WLED_DISABLE_PARTICLESYSTEM2D ; 2D Partikelsystem aus

lib_deps = ${esp8266.lib_deps}
monitor_filters = esp8266_exception_decoder
custom_usermods = Dino_Killswitch